= Organizational SourceCode Dashboard Portal

##### Status
image:https://jenkins.capraconsulting.no/buildStatus/icon?job=Cantara-SourceCodePortal[Build Status]
image:https://www.repostatus.org/badges/latest/active.svg[Project Status: Active – The project has not yet reached a stable, usable state but is being actively developed.]
image:https://snyk.io/test/github/Cantara/SourceCodePortal/badge.svg[Known Vulnerabilities]


Groups documentation from GitHub repositories.

== Pre-requisites

Requires JDK 11.

=== ChromeDriver

_ChromeDriver_ is required for obtaining GitHub access token.

An _OAuth2 App_ must be created for your organization on https://github.com/organizations/YOUR_ORGANIZATION/settings/applications. This is where you find your ClientId and ClientSecret.

An access-token must be generated before you can use this software. Please configure `security.properties` according to `security.properties.sample` and run the test case `ObtainGitHubAccessTokenTestTool`. Configure `security.properties` with `github.client.accessToken=ACCESS_TOKEN`.

[WARNING]
The `ObtainGitHubAccessTokenTestTool` doesn't work for Multi-Factor-Auth, in which prohibits use of `github.client.accessToken`. If access token is not configured; the client_id and client_secret will be applied on all GitHub requests. This is a workaround until oauth is handled by a website redirect scheme.

Ubuntu installation:

`apt-get install chromedriver`

MacOS installation:

`brew install chromedriver`

== Configuration

=== GitHub Webhook

The Source Code Portal is lisenting on push messages from GitHub. This is


= Notes

* Push CommitEvents arrives as single objects.
* Pull CommitEvents arrives as arrays.
