= Organizational SourceCode Dashboard Portal

Groups documentation from GitHub repositories.

== Pre-requisites

Requires JDK 11.

_ChromeDriver_ is required for obtaining GitHub access token.

An _OAuth2 App_ must be created for your organization on https://github.com/organizations/YOUR_ORGANIZATION/settings/applications. This is where you find your ClientId and ClientSecret.

An access-token must be generated before you can use this software. Please configure `security.properties` according to `security.properties.sample` and run the test case `ObtainGitHubAccessTokenTestTool`. Configure `security.properties` with `github.client.accessToken=ACCESS_TOKEN`.

[WARNING]
The `ObtainGitHubAccessTokenTestTool` doesn't work for Multi-Factor-Auth, in which prohibits use of `github.client.accessToken`. If access token is not configured; the client_id and client_secret will be applied on all GitHub requests. This is a workaround until oauth is handled by the website redirect.

Ubuntu installation:

`apt-get install chromedriver`

MacOS installation:

`brew install chromedriver`

